# Day 4

In [3]:
import numpy as np

In [47]:
file = 'example_day4.txt'
def day4 (file):
    with open (file) as f:
        data = f.read().split('\n\n')
    data = [d.split('\n') for d in data]
    data = [[pos for pos in d if d !=''] for d in data]
    numbers = data[0]
    numbers = numbers[0].split(',')
    numbers = [int(n) for n in numbers]
    boards = data[1:]
    boards = [[b.split(' ') for b in board] for board in boards]
    boards = [[[int(b) for b in bor if b!=''] for bor in board] for board in boards]
    boards = [np.array([bor for bor in board if bor != []]) for board in boards]

    selected_numbers=[]
    for n in numbers:
        selected_numbers.append(n)
    #     print('numbers',selected_numbers)
        for board in boards:
            for row in board:
                row2 = [pos for pos in row if pos not in selected_numbers]
    #             print(row2)
                if row2 == []:
                    bingo = row
                    print(bingo)
                    winning_board = board
                    break
            if row2 == []:
                break

        if row2 == []:
            break
    print(selected_numbers)       
    all_unmarked=[]
    for row in winning_board:
        unmarked = [pos for pos in row if pos not in selected_numbers]
#         print(unmarked)
        all_unmarked = all_unmarked + unmarked

    return sum(all_unmarked)*selected_numbers[-1]

In [48]:
day4(file)

[14 21 17 24  4]
[7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24]


4512

In [49]:
file = 'input_day4.txt'
day4(file)

[32 81 21 11 31]
[42, 44, 71, 26, 70, 92, 77, 45, 6, 18, 79, 54, 31, 34, 64, 32, 16, 55, 81, 11, 90, 10, 21]


16674

PART 2

In [2]:
import numpy as np

In [84]:
def day4_2(file):
    with open (file) as f:
        data = f.read().split('\n\n')
    data = [d.split('\n') for d in data]
    data = [[pos for pos in d if d !=''] for d in data]
    numbers = data[0]
    numbers = numbers[0].split(',')
    numbers = [int(n) for n in numbers]
    boards = data[1:]
    boards = [[b.split(' ') for b in board] for board in boards]
    boards = [[[int(b) for b in bor if b!=''] for bor in board] for board in boards]
    boards = [np.array([bor for bor in board if bor != []]) for board in boards]

    selected_numbers = []
    winning_boards = []
    for n in numbers:
        selected_numbers.append(n)
        for board in boards:
            for row in board:
                row2 = [pos for pos in row if pos in selected_numbers]
                if len(row2) == 5:
                    if winning_boards == []:
                        winning_boards.append(board)
                    else:
                        comparisons = [True if elem is board else False for elem in winning_boards]
                        if any (c == True for c in comparisons):
                            pass
                        else:
                            winning_boards.append(board)

                    if len(winning_boards) == len(boards):
                        print('bingo! Row',row)
                        losing_board = board
                        print(board)
                        print(selected_numbers)
                    break
            if len(winning_boards) == len(boards):
                break

            for col in board.T:
                col2 = [pos for pos in col if pos in selected_numbers]
                if len(col2) == 5:
                    if winning_boards == []:
                        winning_boards.append(board)
                    else:
                        comparisons = [True if elem is board else False for elem in winning_boards]
                        if any (c == True for c in comparisons):
                            pass
                        else:
                            winning_boards.append(board)

                    if len(winning_boards) == len(boards):
                        print('bingo! Col',col)
                        losing_board = board
                        print(board)
                        print(selected_numbers)
                    break
            if len(winning_boards) == len(boards):
                break
        if len(winning_boards) == len(boards):
            break

    all_unmarked=[]

    for row in losing_board:
        unmarked = [pos for pos in row if pos not in selected_numbers]
        all_unmarked = all_unmarked + unmarked
    print(sum(all_unmarked))
    print(selected_numbers[-1])
    return sum(all_unmarked) * selected_numbers[-1]

In [85]:
file = 'example_day4.txt'
day4_2(file)


bingo! Col [ 0 13  7 10 16]
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24  4]
 [14 21 16 12  6]]
[7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13]
148
13


1924

In [86]:
file = 'input_day4.txt'
day4_2(file)

bingo! Row [25 22 91 20  2]
[[ 1 27 74 89  4]
 [29  9 78 48 54]
 [10 38 13 40 49]
 [71 73 79 77 17]
 [25 22 91 20  2]]
[42, 44, 71, 26, 70, 92, 77, 45, 6, 18, 79, 54, 31, 34, 64, 32, 16, 55, 81, 11, 90, 10, 21, 87, 0, 84, 8, 23, 1, 12, 60, 20, 57, 68, 61, 82, 49, 59, 22, 2, 63, 33, 50, 39, 28, 30, 88, 41, 69, 72, 98, 73, 7, 65, 53, 35, 96, 67, 36, 4, 51, 75, 24, 86, 97, 85, 66, 29, 74, 40, 93, 58, 9, 62, 95, 91, 80, 99, 14, 19, 43, 37, 27, 56, 94, 25]
283
25


7075