In [26]:
import numpy as np

In [99]:
def day5 (file):
    with open (file) as f:
        data = f.read().split('\n')
    data = [d for d in data if d !='' ]
    data = [d.split(' -> ') for d in data]
    data = [[ num.split(',') for num in d] for d in data]
    print(max(data))
    diagram = np.zeros(shape=(1000,1000))

    segments = []

    for d in data:
        x1 = int(d[0][0])
        x2 = int(d[1][0])
        y1 = int(d[0][1])
        y2 = int(d[1][1])
        if y1 == y2:

            if x1 > x2:
#                 print(y1,y2,x1,x2)
                segment = list(range(x2,x1+1))
#                 print(y1, segment)
                for seg in segment:
                    diagram[seg][y1] = diagram[seg][y1] + 1 

            else:
                segment = list(range(x1,x2+1))
                for seg in segment:
                    diagram[seg][y1] = diagram[seg][y1] + 1 

        elif x1 == x2:
            if y1 > y2:
                segment = list(range(y2,y1+1))
                for seg in segment:
                    diagram[x1][seg] = diagram[x1][seg] + 1 


            else:
                segment = list(range(y1,y2+1))
                for seg in segment:
                    diagram[x1][seg] = diagram[x1][seg] + 1



    print(diagram.T)
    unique, counts = np.unique(diagram, return_counts=True)
    counts_dict = dict(zip(unique, counts))
    
    return counts_dict

In [100]:
file = 'example_day5.txt'
day5(file)

[['9', '4'], ['3', '4']]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


{0.0: 999979, 1.0: 16, 2.0: 5}

In [101]:
file = 'input_day5.txt'
day5(file)

[['989', '73'], ['113', '949']]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


{0.0: 890261, 1.0: 105318, 2.0: 4366, 3.0: 55}

In [98]:
4366+55

4421

PART 2

In [127]:
file = 'example_day5.txt'

def day5_2(file):
    with open (file) as f:
        data = f.read().split('\n')
    data = [d for d in data if d !='' ]
    data = [d.split(' -> ') for d in data]
    data = [[ num.split(',') for num in d] for d in data]
    diagram = np.zeros(shape=(1000,1000))

    segments = []

    for d in data:
        x1 = int(d[0][0])
        x2 = int(d[1][0])
        y1 = int(d[0][1])
        y2 = int(d[1][1])
        if y1 == y2:

            if x1 > x2:
                segment = list(range(x2,x1+1))
                for seg in segment:
                    diagram[seg][y1] = diagram[seg][y1] + 1 

            else:
                segment = list(range(x1,x2+1))
                for seg in segment:
                    diagram[seg][y1] = diagram[seg][y1] + 1 

        elif x1 == x2:
            if y1 > y2:
                segment = list(range(y2,y1+1))
                for seg in segment:
                    diagram[x1][seg] = diagram[x1][seg] + 1 


            else:
                segment = list(range(y1,y2+1))
                for seg in segment:
                    diagram[x1][seg] = diagram[x1][seg] + 1
        else:
            if x1 > x2 and y1 > y2:
                x_segment = list(range(x2,x1+1))
                y_segment = list(range(y2,y1+1))
                x_segment.reverse()
                y_segment.reverse()
            elif x1 > x2 and y2 > y1:
                x_segment = list(range(x2,x1+1))
                y_segment = list(range(y1,y2+1))
                x_segment.reverse()
            elif x2 > x1 and y1 > y2:
                x_segment = list(range(x1,x2+1))
                y_segment = list(range(y2,y1+1)) 
                y_segment.reverse()
            elif x2 > x1 and y2 > y1:
                x_segment = list(range(x1,x2+1))
                y_segment = list(range(y1,y2+1))
            for i in range(0,len(x_segment)):
                x=x_segment[i]
                y=y_segment[i]
                diagram[x][y] = diagram[x][y] + 1 




    print(diagram.T)
    unique, counts = np.unique(diagram, return_counts=True)
    counts_dict = dict(zip(unique, counts))
    return counts_dict

In [128]:
file = 'example_day5.txt'
day5_2(file)

[[1. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


{0.0: 999961, 1.0: 27, 2.0: 10, 3.0: 2}

In [130]:
file = 'input_day5.txt'
counts_dict = day5_2(file)
counts_dict

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


{0.0: 830880,
 1.0: 150446,
 2.0: 16356,
 3.0: 1311,
 4.0: 865,
 5.0: 134,
 6.0: 7,
 7.0: 1}

In [138]:
intersects = []
for key in counts_dict.keys():
    if key >= 2:
        intersect = counts_dict[key]
        intersects.append(intersect)
print(intersects, sum(intersects))

[16356, 1311, 865, 134, 7, 1] 18674
